services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - portainer_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/html
    restart: unless-stopped
    networks:
      - portainer_network
    depends_on:
      - portainer

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/html
    networks:
      - portainer_network

  scira-mcp-chat:
    image: docker.io/pahangkrisdyan/scira-mcp-chat
    platform: linux/amd64
    container_name: scira-mcp-chat
    ports:
      - 3000:3000
    environment:
      - XAI_API_KEY=${XAI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://${SCIRA_DB_USER}:${SCIRA_DB_PASSWORD}@scira-mcp-chat-db:5432/${SCIRA_DB_NAME}
    restart: unless-stopped
    networks:
      - portainer_network
    depends_on:
      - scira-mcp-chat-db

  scira-mcp-chat-db:
    image: postgres:15
    container_name: scira-mcp-chat-db
    environment:
      - POSTGRES_USER=${SCIRA_DB_USER}
      - POSTGRES_PASSWORD=${SCIRA_DB_PASSWORD}
      - POSTGRES_DB=${SCIRA_DB_NAME}
    volumes:
      - scira_mcp_chat_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - portainer_network

volumes:
  portainer_data:
  scira_mcp_chat_db_data:

networks:
  portainer_network:
    driver: bridge